name: affordant_view_model
description: A ViewModel API build on top of the Cubit class from the Bloc library
repository: https://github.com/AffordantSoftware/affordant_foundation
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.0.6

dependencies:    
  affordant_core:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_core

  bloc: ^8.1.2 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

