name: affordant_view_model
description: Affordant business logic components
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.6

dependencies:
  bloc: ^8.1.2
  affordant_core:
    path: ../affordant_core
    
  # affordant_core:
  #   git:
  #     url: git@github.com:AffordantSoftware/affordant_foundation.git
  #     path: affordant_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

