name: affordant_onboarding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  go_router: ^12.1.0
  affordant_navigation:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_navigation
  affordant_view_model:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_view_model
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.3.4
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
