name: affordant_core
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: "none"

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
