name: affordant_core
description: Affordant Software basic types
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
