name: affordant_foundation
description: AffordantSoftware's flutter foundation.
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  affordant_core:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_core
  affordant_view_model:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_view_model
  affordant_auth:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_auth
  affordant_form:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_form
  affordant_navigation:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0