name: affordant_flutter_view_model
description: Flutter binding for affordant_view_model. Built on top of Flutter bloc library
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  affordant_view_model:
    path: ../affordant_view_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
