name: affordant_firebase
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  affordant_auth:
    path: ../affordant_auth
  cloud_firestore: ^4.9.1
  collection: ^1.17.2
  firebase_auth: ^4.7.2
  get_it: ^7.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
