name: affordant_auth
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  firebase_auth: ^4.7.2
  get_it: ^7.6.0
  meta: ^1.9.1
  affordant_bloc:
    path: ../affordant_bloc
  bloc: ^8.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
