name: affordant_auth
description: Affordant Software's system for user authentication
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.0.6

dependencies:
  get_it: ^7.6.0
  meta: ^1.9.1
  affordant_core:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_core
  affordant_view_model:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_view_model
  bloc: ^8.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
