name: affordant_bloc
description: Affordant business logic components
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  bloc: ^8.1.2
  get_it: ^7.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

