name: affordant_form
description: Alternative API to work with form in flutter
repository: https://github.com/AffordantSoftware/affordant_foundation
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  affordant_core:
    git:
      url: git@github.com:AffordantSoftware/affordant_foundation.git
    path: affordant_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true