name: affordant_navigation
description: Affordant Software's navigation system for flutter
repository: https://github.com/AffordantSoftware/affordant_foundation
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  affordant_core:
    git:
      url: https://github.com/AffordantSoftware/affordant_foundation.git
      path: affordant_core
  go_router: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

